---
functional:
  - Пользователь имеет возможность авторизироваться через Github 
  - Пользователь имеет возможность авторизироваться через Github
  - Зарегистрированные пользователи могут войти в свой аккаунт 
  -
non-functional:
  - У сайта есть мобильная версия
  - 
implicit:
  - 
  - 
