---
functional:
  - Пользователь имеет возможность авторизироваться через Github 
  - Пользователь имеет возможность авторизироваться через Discord
  - Зарегистрированные пользователи могут войти в свой аккаунт 
  - Зарегистрированные пользователи могут создать игру с другим игроком
  - Зарегистрированные пользователи могут создать игру с другом
  - Зарегистрированные пользователи могут создать игру с ботом
  - Пользователь имеет возмонжость играть без регистрации
  - Зарегистрированный пользователь может создать свой турнир
non-functional:
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
implicit:
  - Сайт работает не только на ПК, но и на мобильных устройствах
  - Сайт работает быстро и без задержек
